repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-added-large-files

- repo: https://git.iamthefij.com/iamthefij/ansible-pre-commit
  rev: v0.1.2
  hooks:
  - id: encryption-check
    files: ((^|/)encrypted-vault.y[a]{0,1}ml$|.vault$)
