helmOperator:
  create: false
git:
  url: "git@github.com:carpenike/k8s-bootstrap"
  path: "devops"
registry:
  rps: 1
  burst: 1
memcached:
  tolerations:
  - key: "arm"
    operator: "Exists"
additionalArgs:
  - --connect=ws://fluxcloud
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
