---

- name: Deploy Calico Config
  delegate_to: localhost
  command: "{{ item }}"
  become: no
  with_items:
    - kubectl apply -f {{ kubernetes_calico_manifest_file }}
    - calicoctl apply -f {{ kubernetes_calico_bgp_file }}
  register: calico_result
  environment:
    KUBECONFIG: "{{ base }}/kubeconfig"
    CALICO_DATASTORE_TYPE: kubernetes
    CALICO_KUBECONFIG: "{{ base }}/kubeconfig"
  changed_when: "'created' in calico_result.stdout"
  #until: "'created' in calico_result.stdout or 'unchanged' in calico_result.stdout"
  until: calico_result is succeeded
  retries: 6
  delay: 10
  when: kubernetes_pod_network.cni == 'calico'
