---
- include: basics.yml
# - include: firewall.yml
- include: docker.yml
  when: k3s_master_cli is search("--docker") and k3s_worker_cli is search("--docker")
- include: network.yml
- include: disks.yml
  when: ceph.zap_disks == true
