---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: netdata
  namespace: monitoring
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.grafana: semver:~1
spec:
  releaseName: netdata
  chart:
    git: https://github.com/netdata/helmchart
    path: .
    ref: master
  values:
    image:
      repository: netdata/netdata
      tag: v1.19.0
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
        kubernetes.io/tls-acme: "true"
    master:
      database:
        storageclass: rook-ceph-block
      alarms:
        storageclass: rook-ceph-block
    slave:
      tolerations:
        - operator: Exists
      annotations:
        kubernetes.io/ingress.class: nginx
  valueFileSecrets:
    - name: "netdata-helm-values"
