---

- name: Add Flux Repo
  command: "{{ item }}"
  with_items:
    - helm repo add fluxcd https://charts.fluxcd.io
  register: flux_repo_results
  environment:
    KUBECONFIG: "{{ base }}/kubeconfig"
  changed_when: "'has been added to your repositories' in flux_repo_results.stdout"
  until: "'has been added to your repositories' in flux_repo_results.stdout"
  retries: 6
  delay: 10

- name: Deploy Flux
  command: "{{ item }}"
  with_items:
    - helm upgrade --install flux --values {{ base }}/devops/flux/flux/flux-values.yaml --namespace flux fluxcd/flux
    - helm upgrade --install helm-operator --values {{ base }}/devops/flux/helm-operator/flux-helm-operator-values.yaml --namespace flux fluxcd/helm-operator
  register: flux_results
  environment:
    KUBECONFIG: "{{ base }}/kubeconfig"
  changed_when: "'has been upgraded' in flux_results.stdout"
  until: "'has been upgraded' in flux_results.stdout"
  retries: 10
  delay: 10

- name: Get Flux identity
  command: "{{ item }}"
  with_items:
    - fluxctl identity
  register: flux_identity
  environment:
    KUBECONFIG: "{{ base }}/kubeconfig"
    FLUX_FORWARD_NAMESPACE: flux
  until: "'ssh-rsa' in flux_identity.stdout"
  retries: 10
  delay: 10

- name: Register Flux Identity with GitHub
  script: "{{ base }}/setup/add-repo-key.sh '{{ flux_identity.results[0].stdout }}'"
  register: register_result
