apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: vault
  namespace: kube-system
spec:
  releaseName: vault
  helmVersion: v3
  rollback:
    enabled: false
  chart:
    git: https://github.com/hashicorp/vault-helm
    ref: v0.3.3
    path: .
  values:
    injector:
      enabled: false
    server:
      extraVolumes:
        - type: secret
          name: kms-vault
      extraArgs: -config=/vault/userconfig/kms-vault/config.hcl
      tolerations: |
        - key: "arm"
          operator: "Exists"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: vault.holthome.net
            paths:
              - /
        # tls:
        #   hosts:
        #     - vault.holthome.net
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 256Mi
      standalone:
        enabled: "false"
      ha:
        enabled: "true"
        config: |
          ui = true
          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }
          storage "consul" {
            path = "vault"
            address = "HOST_IP:8500"
          }
