---

- name: apply storage annotations
  ignore_errors: yes
  command: kubectl label node {{ item }} node-role.kubernetes.io/storage=true
  with_items:
    - r610-0
    - r610-1
    - r610-2
  environment:
    KUBECONFIG: "{{ base }}/setup/kubeconfig"

- name: apply worker annotations
  ignore_errors: yes
  command: kubectl label node {{ item }} node-role.kubernetes.io/worker=true
  with_items:
    - r610-0
    - r610-1
    - r610-2
    - n2-0
  environment:
    KUBECONFIG: "{{ base }}/setup/kubeconfig"

- name: apply master annotations
  ignore_errors: yes
  command: kubectl taint --overwrite node {{ item }} node-role.kubernetes.io/master=true:NoSchedule
  with_items:
    - k3s-master-a
  environment:
    KUBECONFIG: "{{ base }}/setup/kubeconfig"
